/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthOptimizerRouteImport } from './routes/_auth.optimizer'
import { Route as AuthCutsRouteImport } from './routes/_auth.cuts'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOptimizerRoute = AuthOptimizerRouteImport.update({
  id: '/optimizer',
  path: '/optimizer',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCutsRoute = AuthCutsRouteImport.update({
  id: '/cuts',
  path: '/cuts',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cuts': typeof AuthCutsRoute
  '/optimizer': typeof AuthOptimizerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cuts': typeof AuthCutsRoute
  '/optimizer': typeof AuthOptimizerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/cuts': typeof AuthCutsRoute
  '/_auth/optimizer': typeof AuthOptimizerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cuts' | '/optimizer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cuts' | '/optimizer'
  id: '__root__' | '/' | '/_auth' | '/_auth/cuts' | '/_auth/optimizer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/optimizer': {
      id: '/_auth/optimizer'
      path: '/optimizer'
      fullPath: '/optimizer'
      preLoaderRoute: typeof AuthOptimizerRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cuts': {
      id: '/_auth/cuts'
      path: '/cuts'
      fullPath: '/cuts'
      preLoaderRoute: typeof AuthCutsRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCutsRoute: typeof AuthCutsRoute
  AuthOptimizerRoute: typeof AuthOptimizerRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCutsRoute: AuthCutsRoute,
  AuthOptimizerRoute: AuthOptimizerRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
